version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: rpn_cb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpn_cb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: "Asia/Jakarta"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rpn_cb_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  mysql_data:
