FROM php:8.2-apache

# Install ekstensi PHP yang dibutuhkan
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Salin semua file proyek CI4 ke dalam container
COPY . /var/www/html/

# Atur working directory
WORKDIR /var/www/html/

# Berikan izin untuk writable directory (cache, logs, dll)
RUN chmod -R 777 /var/www/html/writable

# Atur Apache agar dapat mengakses folder public
RUN echo "DocumentRoot /var/www/html/public" > /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

RUN apt-get update && apt-get install -y libicu-dev
RUN docker-php-ext-install intl
